FROM python:3
COPY ./requirements.txt /app/requirements.txt
COPY ./app.py /app/app.py
COPY ./model.py /app/model.py
WORKDIR /app
RUN pip install -r requirements.txt
COPY . /app
ENTRYPOINT [ "gunicorn", "--bind 0.0.0.0:5000", "app:app"]